const EFFECTIVE_DATE = "April 23, 2026";
const CONTACT_EMAIL = "afsarzahin@gmail.com";

export default function TermsPage() {
  return (
    <main className="min-h-screen px-6 py-16 relative">
      <div className="aurora"><span /></div>
      <div className="grid-overlay" />
      <div className="noise" />

      <div className="relative z-10 max-w-3xl mx-auto">
        <div className="text-center mb-8 fade-up">
          <a href="/" className="font-bold tracking-tight text-xl text-gradient">
            KeepMyMotivation
          </a>
        </div>

        <article className="glass p-8 md:p-10 fade-up delay-100 space-y-6 text-[color:var(--muted)]">
          <header>
            <h1 className="text-3xl font-bold text-gradient mb-2">Terms & Conditions</h1>
            <p className="text-sm">Effective {EFFECTIVE_DATE}</p>
          </header>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-white">1. Acceptance</h2>
            <p>
              By creating an account or using KeepMyMotivation (the &quot;Service&quot;), you agree to these
              Terms. If you do not agree, do not use the Service.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-white">2. The Service</h2>
            <p>
              KeepMyMotivation sends you personalized motivational emails based on goals you provide,
              on a cadence tied to your plan. Content is generated with AI and is for personal
              encouragement only — not professional, medical, legal, or financial advice.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-white">3. Accounts</h2>
            <p>
              You must provide a valid email and keep your PIN confidential. You are responsible for
              activity under your account. You must be at least 13 years old to use the Service.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-white">4. Plans & Billing</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>Spark: 1 email / month, free.</li>
              <li>Boost: 1 email / week, paid subscription.</li>
              <li>Drive: 1 email / day, paid subscription.</li>
            </ul>
            <p>
              Paid subscriptions are processed by Lemon Squeezy and renew automatically until
              cancelled. You can cancel anytime; cancellation stops future renewals and keeps access
              until the current period ends.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-white">5. Refunds</h2>
            <p>
              All payments are non-refundable. Cancelling a subscription prevents future charges but
              does not refund past payments, including unused portions of a billing period.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-white">6. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Submit goals containing illegal, harmful, hateful, or sexual content involving minors.</li>
              <li>Use the Service to harass, defraud, or harm others.</li>
              <li>Reverse engineer, scrape, or abuse the Service or its AI outputs.</li>
              <li>Resell or redistribute generated emails without permission.</li>
            </ul>
            <p>We may suspend or terminate accounts that violate these rules.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-white">7. AI-Generated Content</h2>
            <p>
              Emails are generated by large language models and may be inaccurate, generic, or
              unexpected. You use them at your own discretion. We do not guarantee any particular
              outcome, motivation level, or result from using the Service.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-white">8. Your Data</h2>
            <p>
              We store the goals and preferences you provide to generate and deliver your emails. We
              use third-party providers (including OpenAI, Resend, Pexels, and Lemon Squeezy) to
              operate the Service. You may request deletion of your account and associated data at
              any time by emailing us.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-white">9. Intellectual Property</h2>
            <p>
              The Service, including its design, code, and branding, is owned by KeepMyMotivation.
              You retain ownership of goals you submit and grant us a limited licence to use them to
              operate the Service.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-white">10. Disclaimer</h2>
            <p>
              The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind. We
              do not guarantee uninterrupted delivery, error-free emails, or fitness for a particular
              purpose.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-white">11. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, KeepMyMotivation is not liable for any
              indirect, incidental, or consequential damages. Our total liability for any claim
              arising from the Service is limited to the amount you paid us in the 12 months before
              the claim.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-white">12. Termination</h2>
            <p>
              You may stop using the Service at any time. We may suspend or terminate your access if
              you breach these Terms or abuse the Service.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-white">13. Changes</h2>
            <p>
              We may update these Terms. Material changes will be announced via email or in-app
              notice. Continued use after changes means you accept the updated Terms.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-white">14. Governing Law</h2>
            <p>
              These Terms are governed by the laws of Bangladesh. Disputes will be resolved in the
              courts of Bangladesh.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-white">15. Contact</h2>
            <p>
              Questions about these Terms:{" "}
              <a
                href={`mailto:${CONTACT_EMAIL}`}
                className="text-white hover:underline"
              >
                {CONTACT_EMAIL}
              </a>
              .
            </p>
          </section>
        </article>

        <p className="text-center text-sm text-[color:var(--muted)] mt-6">
          <a href="/" className="hover:text-white">← Back to home</a>
        </p>
      </div>
    </main>
  );
}
